### ISSUE TITLE
IPLD Roadmap 2016Q4

### ISSUE THREAD

**Issue by nicola** [ipld/ipld#3]
(Summary of conversations and planning)

## Overall Outcomes
Ship IPLD, from libraries to documentation

- IPLD support
  - Usable libraries
  - IPLD-cli support
  - IPFS on IPLD
- IPLD website
  - Examples
  - Tutorial
  - Playground
  - Logo
- IPLD paper
- IPLD and CID spec

---

## Timeline

Nov 20
- [ ] Finalize IPLD Paper ( @nicola ) (was Oct 24)
- [ ] Website Iteration 1 https://github.com/ipld/website/issues/14 ( @VictorBjelkholm )
- [ ] Write down CID spec (super-alpha!)

Dec 5
- [ ] Write IPLD content (tutorial/example) for the website https://github.com/ipld/website/issues/13 ( @RichardLitt, @nicola )

Dec 12
- [ ] Ship logo for IPLD https://github.com/ipld/ipld/issues/5 ( **?**, @flyingzumwalt, @dignifiedquire, @jesseclay ?)
- [ ] [Ship Website+Playground](https://github.com/ipld/website/milestone/1) ( @VictorBjelkholm )

Dec 19
- [ ] Ship Spec for IPLD and CID https://github.com/ipld/specs/issues/31 https://github.com/ipld/specs/issues/32 ( @nicola )

---

### Need timing

The following **must happen** by this quarter deadline (end of December), it would be great to correctly place on the timeline and link them to the current issues happening

Need timing:
- [ ] Release IPLD libraries (@diasdavid)
- [ ] Add IPLD-cli support (dag) https://github.com/ipfs/interface-ipfs-core/issues/81 (@diasdavid, @whyrusleeping ?)
- [ ] Create IPLD namespace (@jbenet ?)
- [ ] Complete IPFS on IPLD (@diasdavid, @lgierth ?)
- [ ] Complete Playground (@dignifiedquire, @VictorBjelkholm )
