### ISSUE TITLE
2021 Site Launch Checklist

### ISSUE THREAD

**Issue by warpfork** [ipld/ipld#96]
This issue is a big (big) checklist of work still todo in the new docs & specs & site work, which is currently ongoing in the "[2021](https://github.com/ipld/ipld/tree/2021)" branch.

The previews of the built site can be seen here: https://empty-grass-9837.on.fleek.co/

This checklist is probably mostly for me to self-organize, but also for public view, and optimistically, if anyone can spot things they could jump in on... sweet.  :)

(The work already done on that branch isn't reflected here... so this is going to look like a lot of empty checkboxes, but in reality, a huge majority of the total work needed in this process is already done; I'm just not making feel-good checkboxes for all that stuff.)

I haven't completely sifted these for what's a critical need for launch, vs what are nice to have.  I will also keep editing this issue and the list may shift in ways other than just checking off this first round of boxes.

---

### Content-heavy work

(A lot of this is still probably for me, but if anyone sees things they could pick up, sweeeet)

- [ ] ADL docs still need a lot of work.
  - [ ] Split it up into multiple pages!  WAY too much going on here for one page!
  - [ ] examples of user stories.
  - [ ] invest heavily in making "the signalling problem" and its various options for solutions are clear.
    - [ ] should now include links to the go-ipld-prime NodeReifier API, which actually gives us a concrete example of how to solve this.
  - [ ] We probably need a list of links to known libraries and implementations of these.  Not sure exactly where to organize that.
    - [ ] A page per language in the libraries chapter?
    - [ ] A unified table in the ADL docs chaper could be good.  (Highlights clearly which major languages have an implementation.  But possibly not scalable.)
  - [ ] We should introduce the "substrate" vs "synthesized" terminology.  (Probably.  We might still argue about the names.)
  - [ ] There's a huge todo section about "practical implications".  This needs filling out.  The todo block contains details.
    - [ ] Especially, this needs to communicate the virtues of using common ADLs rather than rolling your own (without a very good reason).
- [x] Schema docs need reorganization.  (A lot of the content is good, but the walk order one should take is very unclear right now.)
  - [ ] Schema chapter intro page is... just... reboot that one.
- Schema doc content...
  - [ ] Schema docs need to present the "try stack"/"unification" concept and other migration-related stories better.  There is text about this, but people seem not to find that page or recognize it.  (I don't know what's missing; I can only observe I frequently get asked about this.)
  - [ ] Documentation around how to signal the use of ADLs within schemas needs review.  There's a large hunk in the schema docs, but it's not connected to the ADL docs on "the signalling problem" (big whoopsie!), I'm not sure the syntax shown there is up to date either; and there should be caveats about the level of deployment of those features.
  - [ ] Some things that are currently "docs" should probably be re-homed under "specs".  ("specs" is currently pretty empty.)
  - [ ] Review for any missing or under-defined representation strategies.
  - [ ] Make sure there are good short sensible direct link slugs for the representation strategies.
  - [ ] Representation strategies should probably have a summary table somewhere.  Some single spot which communicates the range of features available (and also fish-slaps you with the non-1:1 of type-kind to representation-kind).
  - [ ] Review the entire thing for consistent use of terminology around type-kinds vs representation kinds.  (TODO: link to issue where we last discussed this terminology.)  (This will be fairly grueling.)
- [ ] Codec specs need more rigor.
  - I'm not going to go into detail on this here.  And probably not even try to solve it today, because it's too huge, and needs a team and consensus forming.  Just note that there's a lot of work to be done here.
- [ ] Codec docs need fleshing out.  Can be brief, but should guide users towards which codecs to consider and why.
  - [ ] A consistent set of sections (e.g. "considerations", "completeness", "performance", etc) would be a great start.
- [ ] Codec specs and docs should link back and forth to each other consistently, and in a decorated way (small boilerplate explanatory note with the link, some emoji/icon, etc).  Making a small shortcode or similar for this would be appropriate.
- [ ] Selector specs need more examples.
  - [ ] The existing examples need to be fixed to not be YAML.  That's turned out to be really confusing for people.  Just show them the full ugly real json, and put an explainer on the side.
  - [ ] Examples/fixtures showing how walking works, and disambiguates visit vs match, are needed.
  - [ ] Examples/fixtures demonstrating order stability during walks are needed.
- [x] Port the "brief primer" (currently a hackmd document, floating somewhere).
- [ ] Migrate the "codecs and completeness" doc, and integrate it better.
  - [ ] Review the terminology proposed in it;
  - [ ] *use those terms* in the docs and specs for codecs, so that limitations and features are precisely and consistently described.
  - [ ] Format the doc such that the terminology definitions can be jumped to with direct links.  (May need some manual html.)
- [ ] **Data Model docs**.
  - [ ] "Traversals" still need their page filled in.  (Somehow, we didn't talk about this nearly enough in any of the old docs and specs content!)
  - [x] "Node" page still needs filling in.  There is probably some content to use here from the old "library recommendations" pages, but I think we need to hoist that into a general concept rather than tucking it off as if its an implementation detail in a distant corner.
  - [ ] Overview page needs some review.  It's currently really wordy and I think it should be shorter and just routing you quickly to the sub-pages.
  - [ ] The "motivation" section from the overview page should be extracted and go... somewhere else.  Possibly a subpage; possibly the design chapter; possibly the docs/motivation/ area; unsure.
- The "how IPFS web gateways work" doc...
  - [ ] Fix the formatting.  It wasn't ported very well.
  - [ ] Finish all the content todos in it.  There are several.
  - [ ] Update it to describe and link to all the awesome recent work on unixfsv1-as-ADLs!
  - [ ] Maybe debate how we want to frame the meaning of "gateway" here (re: the contemporary discussions about if "gateways" are supposed to provide a good experience for raw IPLD or are *just* unixfsv1-file-over-http emitters).
- [ ] Do a quick review on the "getting things done" doc and its internal linking.  It's close, just could use a fresh coat of paint, a linked TOC, and probably more connective linking to other pages for details.
  - [ ] Consider writing a dark mirror of itself in the trailing half of the document: why _not_ use feature X to accomplish goal Y, etc.  These are useful to have as direct links when having code or design review disucssions.
- [ ] Port ADL specs!
  - [x] Port the HAMT specs.
  - [x] Port the FBL specs.
  - [ ] Port the AMT specs.
  - Others?
- [ ] Figure out which heading to migrate the graphsync docs and specs into.
- [x] Introduce "transport" chapter in docs.
  - (or find a better name for it.  Consider the content below which seems to go in this heading.)
  - [ ] Slightly deeper coverage to "blocks" than the glossary currently gives.
  - [ ] Graphsync may go here?  Or bitswap?  At least brief mentions of them.
  - [ ] Discussion of "datastore" interfaces as an API concept may go here?
  - [ ] Crosslink this heavily with a page in the design chapter that talks about content-addressing as a concept.
- [x] Port Ethereum codec docs.

(In general: anything in the `_legacy/*` dir tree still needs porting, or to be definitively dismissed.  If this issue is out of sync with that, then git is going to be a better source of truth than this issue.)

### Things I could use an assist on

(and things that just involve crosslinking to *yet other* docs which exist on different domains.)

- [ ] Connect any mentions of CIDs and Linking to the relevant Protoschool tutorials or other primary resources.
  - [ ] Determine if the canonical place for CID specs is here.  Because we have some (still in the `_legacy` dir, not ported yet).  Or should these be removed from this repo / stripped down to just a glossary entry, because they have a home elsewhere?
- [ ] Connect any mentions of multiformats indicators and multicodecs to the relevant Protoschool tutorials or other primary resources.
- [ ] Review the what-is-ipld graphic, with someone who groks information ontology and also is a bit farther from the topic.  It's close, but still misleads in some critical ways, and needs a spark of... something.
  - [ ] Also, ensure that information is available accessibly.  The image is great, but text-heavy.  Great for conference slides; Doesn't present well on small screens.  Some alternates would be good.

More content:

- [ ] Fill in the synopsis for everything!  You'll see the placeholder text across the site.  Almost every page needs this at the moment.
- [ ] The library javascript docs are a huge blank spot.  We have old and new generations in javascript, too, so we need to offer guidance to users here.  (@rvagg, please?)
- [ ] The tools pages could have a *ton* of fun content.
  - [ ] @rvagg's schema-inferrer tool.
  - [ ] @rvagg's schema syntax highlighter IDE plugins.
  - ... a bunch of other fun things like this I can't all enumerate off top of head!  (Which is why we need these pages!)
- [ ] Review the /docs/motivation/ section.  It currently has one doc.  It should either have more than one, or.... we should figure out some other place to tuck that thing.
  - [ ] The "data to data structures" story is nice but needs some editing.  A summary to bring it together at the end would help a great deal.  Perhaps some connective tissue and 'read next" links.
- [ ] Could we make any more "synthesis" docs?  Those are nice.  (I don't have concrete ideas at the moment.)
- [ ] Figure out what to do with the filecoin docs, currently under `_legacy/data-structures`.  They're not a (single) ADL.  They're not a codec.  What are they?  Does this even belong in this repo?  Is it an "examples in the wild" type thing?

Styling:

- [ ] Logo.
- [ ] Code blocks could use some prettifying.
- [ ] Do the highlight for active page in the nav.  (Easy.)
- [ ] Wishlist: folding the nav for major chapters.  Default to folding any of them you're not in.
- [ ] Wishlist: there are some pages that may not be not worth showing in the nav list unless you're near them (codecs are the obvious example).  Or, maybe they should just get smaller fonts.  _Something_ to make the list not overwhelming.
- [ ] Consider: color or other cues for which major chapter you're in (e.g. docs vs specs).

### things that are probably still far future

- [ ] Web-executable editable schema match examples.  (Something like the "go run" feature in godocs.  The schema could be fixed, but the user should be able to edit the example json and see how it's morphed to the type info (or why it's rejected as mismatch).)
- [ ] Web-executable editable schema match examples -- now with editable schema, too.  (This may be a slightly farther stretch than the above, or it might be easy.  Not sure.)
- [ ] Web-executable editable selector examples.

**Comment by BigLep** [comment]
@warpfork : just checking in on if we're going to be able to cut over to the new doc pages.

**Comment by warpfork** [comment]
Yeah, I think we're good to progress on this.  There's still a lot of boxes to check that are wants, but in the last couple days I've ported almost everything super critical, and we're more comprehensive in the new stuff than the old stuff.

I updated the master branch of this repo to point to the new content (and merged the old master content into the `_legacy` dir, as with all the others that have been unified) on friday.

I believe the infra is staged and ready to go (the team owning that has already replicated the site build to within the PL team Fleek account).  I sent a support request to the keepers of the DNS entries at the end of last week and I think we go live soon!

**Comment by BigLep** [comment]
@warpfork : it looks like the site is live now right?  Sweet!

**Comment by warpfork** [comment]
DNS update confirmed!  https://ipld.io/ is now live with the new content.

I think I'm going to do one more review pass over more of the "first impressions" (most of this has been "deep content" work, by contrast) before going on blast with shipped announcements.

It's now also time to start doing redirect pointers in all the old content, and eventually, marking those repos archived.  I'd been putting that off until we crossed at least the line of getting new consolidated content on the master branch in this repo, but we're now there.

**Comment by warpfork** [comment]
Okay -- this issue may be deserving some review.  It's currently at "7 of 78 tasks", github helpfully counts.

Most of these checkboxes are a huge laundry list of things that are probaby worth doing, but are in _nice to have_ territory.  They're things we can keep working on, opportunistically, over time.  They're not a march to any kind of pressing finish line right now.

(So if this is on any kind of project board view, it's probably representing itself badly.)

Meanwhile, the site has indeed actually launched.  So "launch checklist" is _definitely_ a misnomer.

Maybe it's time to close this?  If not, at least renaming it seems due.

I'm fine with closing it, but if we do, would note that I don't think I can be bothered to open new issues for all the individual checkmarks, either.  Even if the wishes are accurate, that's just a ghastly large amount of clicking around in the github UI.

**Comment by warpfork** [comment]
Thinking out loud on a post-launch checklist, the biggest remaining todos are probably:
- [ ] redirect `docs.ipld.io` to the bare domain, to remove confusing replication of any information there
- [ ] make a push on putting tombstone markers in `ipld/specs` and those other repos

We've started doing the latter opportunistically, but it would probably be a good idea to allocate a time block to doing it uniformly on all content, rather than just the content we've touched again recently.

**Comment by warpfork** [comment]
Closing this.  Site is launched.  Continuing work deserves new issues.

**Comment by BigLep** [comment]
These are the closeout we'll do for this season on the docs site:
https://github.com/ipld/ipld/issues/123
https://github.com/ipld/ipld/issues/124
https://github.com/ipld/ipld/issues/125
https://github.com/ipld/ipld/issues/126
